version: '3'

services:

  mongo:
    image: mongo
    ports:
        - 3000:27017
    volumes:
        - ./docker/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
        - mongo-data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: pindureta

volumes:
    mongo-data:
        driver: local